# Generated by Django 5.0.1 on 2024-01-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
