# Generated by Django 5.0.1 on 2024-01-31 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0006_userroles_user_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroles',
            old_name='Designation',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='userroles',
            old_name='Name',
            new_name='name',
        ),
    ]
